language: node_js
node_js:
  - "10"
os:
  - linux

cache:
  directories:
    - "node_modules"

stages:
  - name: test
  - name: deploy

jobs:
  include:
    - stage: test
      script:
        - yarn
        - npm run test
    - stage: deploy
      script: skip
      deploy:
        provider: npm
        email: gaoxiaosong06@gmail.com
        api_key: "$NPM_TOKEN"
        on:
          tags: true