language: node_js
node_js:
  - "10"
os:
  - linux

cache: yarn

stages:
  - name: test
  - name: deploy
    if: tag IS present

jobs:
  include:
    - stage: test
    - stage: deploy
      script: skip
      before_deploy:
        - yarn
        - yarn run build
        - ls
      deploy:
        provider: npm
        email: gaoxiaosong06@gmail.com
        api_key: "$NPM_TOKEN"
        on:
          tags: true